version: "3.9"

services:
  db:
    image: postgres:15
    container_name: parkingbuddies-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1103
      POSTGRES_DB: parkingbuddies
    volumes:
      - parkingbuddies_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d parkingbuddies"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  parkingbuddies_pgdata:
